import { createFileRoute, Link } from "@tanstack/react-router";
import { GlassCard, PageHeader, SectionHeader } from "@/components/sq/glass-card";
import { formatDistanceToNow } from "date-fns";
import { useInvestigations } from "@/lib/live-queries";
import { FileSearch2, Upload } from "lucide-react";
import { usePrefs, formatMoney } from "@/lib/currency";

export const Route = createFileRoute("/_app/investigations")({
  ssr: false,
  component: InvPage,
});

function InvPage() {
  const { data: invs = [], isLoading } = useInvestigations();
  const prefs = usePrefs();

  return (
    <div>
      <PageHeader title="AI Investigations" subtitle="Auto-generated by the Correlation Engine · each investigation is grounded on live evidence." />
      <div className="grid grid-cols-12 gap-4">
        {isLoading && <GlassCard className="col-span-12"><div className="text-xs text-muted-foreground p-4">Loading…</div></GlassCard>}
        {!isLoading && invs.length === 0 && <GlassCard className="col-span-12"><div className="text-xs text-muted-foreground p-4">No investigations yet. Simulate a transaction to generate one.</div></GlassCard>}
        {invs.map((i) => (
          <GlassCard key={i.id} className="col-span-12 md:col-span-6 xl:col-span-4">
            <div className="flex items-start gap-3">
              <div className="h-10 w-10 rounded-xl grid place-items-center hairline"><FileSearch2 className="h-5 w-5 text-violet-300" /></div>
              <div className="flex-1 min-w-0">
                <div className="text-sm font-semibold truncate">{i.title}</div>
                <div className="text-[11px] text-muted-foreground">{i.attack_type ?? "—"} · {formatDistanceToNow(new Date(i.created_at), { addSuffix: true })}</div>
              </div>
              <div className="text-right">
                <div className="text-[10px] uppercase text-muted-foreground">Conf.</div>
                <div className="text-sm font-mono text-cyan-300">{i.confidence}%</div>
              </div>
            </div>
            <div className="mt-3">
              <SectionHeader title="Root cause" />
              <div className="text-xs text-muted-foreground leading-relaxed line-clamp-4">{i.root_cause ?? "—"}</div>
            </div>
            <div className="mt-3 flex flex-wrap gap-1">
              {(Array.isArray(i.risk_factors) ? i.risk_factors as string[] : []).slice(0, 4).map((f, idx) => (
                <span key={idx} className="text-[10px] px-1.5 py-0.5 rounded bg-white/6">{f}</span>
              ))}
            </div>
            <div className="mt-3 flex items-center justify-between">
              <div className="text-[11px] text-muted-foreground">Impact: <span className="text-foreground font-mono">${Number(i.business_impact ?? 0).toLocaleString()}</span></div>
              <Link to="/correlation" className="text-[11px] text-cyan-300 hover:underline">Open in Correlation →</Link>
            </div>
          </GlassCard>
        ))}
      </div>
    </div>
  );
}
